name: execu_docs
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  go_router: ^16.0.0
  path_provider: ^2.1.5
  get_it: ^8.2.0
  injectable: ^2.5.1
  file_picker: ^10.2.1
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.38
  path: ^1.9.1
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  window_manager: ^0.5.1

  xml: ^6.6.1
  freezed_annotation: ^3.1.0
  collection: ^1.19.1
  cleartec_docx_template: ^0.4.1
  archive: ^3.6.1
  flutter_slidable: ^4.0.1
  equatable: ^2.0.7
  percent_indicator: ^4.2.5
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  drift_dev: ^2.17.0
  freezed: ^3.2.0
  injectable_generator: ^2.8.1



flutter:
  assets:
    - assets/scripts/merge_docs.vbs
    - assets/scripts/unite_files.vbs
    - assets/templates/template.docx
    - assets/templates/template_ternopil.docx
    - assets/templates/empty_template.docx
    - assets/templates/empty_resolution_template.docx


  uses-material-design: true
